name: labeler

on: [pull_request]

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/XS'
          xs_max_size: '9'
          s_label: 'size/S'
          s_max_size: '29'
          m_label: 'size/M'
          m_max_size: '99'
          l_label: 'size/L'
          l_max_size: '499'
          xl_label: 'size/XL'
          xl_max_size: '999'
          xxl_label: 'size/XXL'
          fail_if_xxl: 'false'
          github_api_url: 'api.github.com'
          files_to_ignore: ''